name: mobile
description: "Registro Panela mobile app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  cloud_firestore: ^6.2.0
  firebase_core: ^4.6.0
  flutter_riverpod: ^3.1.0
  go_router: ^17.2.0
  intl: ^0.20.2
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  printing: ^5.11.0
  uuid: ^4.5.1
  collection: ^1.19.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  fonts:
    - family: RobotoVariableItalic
      fonts:
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          weight: 400
          style: normal

flutter_native_splash:
  color: "#F5EFE1"
  image: assets/images/logo_splash.png
  android: true
  ios: true
  android_12:
    image: assets/images/logo_splash.png
    color: "#F5EFE1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo_icono.png
  remove_alpha_ios: true
  adaptive_icon_background: "#F5EFE1"
  adaptive_icon_foreground: assets/images/logo_icono.png
  adaptive_icon_foreground_inset: 16